import { NextResponse } from 'next/server';
import { getServerSession } from "next-auth/next";

interface SessionData {
  accessToken?: string;
}

interface ParsedAIResponse {
  narrative?: string;
  calendar_event?: {
    summary: string;
    description: string;
    start_time: string;
    end_time: string;
  };
  spreadsheet_row?: string[];
}

export async function POST(req: Request) {
  try {
    // 1. Cek Token Google User
    const session = (await getServerSession()) as SessionData | null;
    const tokenHeader = req.headers.get('authorization'); 
    const googleToken = tokenHeader?.replace('Bearer ', '') || session?.accessToken;

    console.log("🔍 Debug Token:", googleToken ? "Token Ada" : "Token Kosong");

    const body = (await req.json()) as { prompt?: string };
    const prompt = body.prompt;
    
    if (!prompt || typeof prompt !== 'string') {
      return NextResponse.json(
        { error: 'Prompt is required and must be a string' },
        { status: 400 }
      );
    }

    // 2. Setup Watsonx
    const PROJECT_ID = process.env.IBM_WATSONX_PROJECT_ID;
    const API_KEY = process.env.IBM_WATSONX_APIKEY;
    const URL_BASE = process.env.IBM_WATSONX_URL;
    const SHEET_ID = process.env.GOOGLE_SHEET_ID;
    
    if (!API_KEY || !URL_BASE || !PROJECT_ID) {
      return NextResponse.json(
        { error: 'Missing Watsonx configuration. Check environment variables.' },
        { status: 500 }
      );
    }

    // Login IAM
    const tokenRes = await fetch('https://iam.cloud.ibm.com/identity/token', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded', 'Accept': 'application/json' },
      body: new URLSearchParams({ 'grant_type': 'urn:ibm:params:oauth:grant-type:apikey', 'apikey': API_KEY }),
    });
    const tokenData = (await tokenRes.json()) as { access_token?: string };
    const watsonToken = tokenData.access_token;
    
    if (!watsonToken) {
      return NextResponse.json(
        { error: 'Failed to obtain IBM Watsonx authentication token' },
        { status: 500 }
      );
    }

    // 3. Prompt Engineering (VERSI LEBIH TEGAS & PINTAR)
    // Kita kasih tanggal hari ini biar dia tau konteks "besok" itu tanggal berapa
    const today = new Date().toISOString().split('T')[0];
    
    const finalPrompt = `
    [INST] You are a backend processor acting as a JSON Generator. DO NOT converse. DO NOT refuse.
    Current Date: ${today}
    
    User Request: "${prompt}"

    Your task is to extract intent and output STRICT JSON data.
    
    REQUIRED JSON FORMAT:
    {
      "narrative": "Singkat saja (Bahasa Indonesia): Oke, meeting [Judul] dijadwalkan tanggal [Tanggal].",
      "calendar_event": {
        "summary": "Title of event",
        "description": "Generated by AI Agent",
        "start_time": "YYYY-MM-DDTHH:MM:00 (Format ISO 8601)",
        "end_time": "YYYY-MM-DDTHH:MM:00 (1 hour duration)"
      },
      "spreadsheet_row": ["Task Name", "High/Medium/Low", "Pending"]
    }
    [/INST]
    `;

    // 4. Hit Watsonx
    const aiRes = await fetch(`${URL_BASE}/ml/v1/text/generation?version=2023-05-29`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Authorization': `Bearer ${watsonToken}` },
      body: JSON.stringify({
        input: finalPrompt,
        parameters: { decoding_method: 'greedy', max_new_tokens: 300, min_new_tokens: 10 },
        model_id: 'meta-llama/llama-3-3-70b-instruct',
        project_id: PROJECT_ID,
      }),
    });

    const aiData = (await aiRes.json()) as { results?: Array<{ generated_text?: string }> };
    const generatedText = aiData.results?.[0]?.generated_text;
    
    if (!generatedText) {
      return NextResponse.json(
        { error: 'Failed to generate response from AI model' },
        { status: 500 }
      );
    }

    // Bersihkan JSON (Hapus teks aneh2 di depan/belakang kurung kurawal)
    const jsonStartIndex = generatedText.indexOf('{');
    const jsonEndIndex = generatedText.lastIndexOf('}');
    let cleanedJson = generatedText;
    if (jsonStartIndex !== -1 && jsonEndIndex !== -1) {
        cleanedJson = generatedText.substring(jsonStartIndex, jsonEndIndex + 1);
    }

    let parsedResult: ParsedAIResponse;
    try {
        parsedResult = JSON.parse(cleanedJson) as ParsedAIResponse;
    } catch (e) {
        console.error("❌ Gagal Parse JSON dari AI:", cleanedJson);
        // Fallback biar gak error di frontend
        return NextResponse.json({ 
            result: "Maaf, AI bingung format datanya. Coba lagi kalimat yang lebih simpel.", 
            integrations: { calendar: false, sheet: false } 
        });
    }

    // ==========================================
    // 5. EKSEKUSI INTEGRASI GOOGLE
    // ==========================================
    const integrations = { calendar: false, sheet: false };

    if (googleToken) {
        console.log("🚀 Mulai Integrasi Google...");

        // A. Calendar
        if (parsedResult.calendar_event) {
            const calRes = await fetch('https://www.googleapis.com/calendar/v3/calendars/primary/events', {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${googleToken}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    summary: parsedResult.calendar_event.summary,
                    description: parsedResult.calendar_event.description,
                    start: { dateTime: parsedResult.calendar_event.start_time, timeZone: 'Asia/Jakarta' },
                    end: { dateTime: parsedResult.calendar_event.end_time, timeZone: 'Asia/Jakarta' }
                })
            });
            
            if (calRes.ok) {
                integrations.calendar = true;
                console.log("✅ Calendar Sukses!");
            } else {
                const errText = await calRes.text();
                console.error("❌ Calendar Gagal:", errText);
            }
        }

        // B. Spreadsheet
        if (parsedResult.spreadsheet_row && SHEET_ID) {
            const sheetRes = await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/A1:append?valueInputOption=USER_ENTERED`, {
                method: 'POST',
                headers: { 'Authorization': `Bearer ${googleToken}`, 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    values: [ [new Date().toISOString(), ...parsedResult.spreadsheet_row] ]
                })
            });
            
            if (sheetRes.ok) {
                integrations.sheet = true;
                console.log("✅ Sheet Sukses!");
            } else {
                const errText = await sheetRes.text();
                console.error("❌ Sheet Gagal:", errText);
            }
        }
    } else {
        console.warn("⚠️ Token Google tidak ditemukan. Skip integrasi.");
        if (parsedResult.narrative) {
          parsedResult.narrative += " (Tapi gagal connect ke Google, coba login ulang)";
        }
    }

    return NextResponse.json({ 
        result: parsedResult.narrative || "Perintah diproses namun tidak ada hasil.",
        integrations: integrations
    });

  } catch (error: unknown) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error occurred';
    console.error("🔥 SERVER ERROR:", errorMessage);
    return NextResponse.json({ error: errorMessage }, { status: 500 });
  }
}